spring:
  port: 8080
  servlet:
    context-path: /logger
  profiles:
    active: log4j2
  datasource:
    url: jdbc:postgresql://47.111.1.69:5432/developer_testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&yearIsDateType=false&allowMultiQueries=true
    username: postgres
    password: YTyjy2018

