spring:
  datasource:
    url: jdbc:postgresql://47.111.1.69:5432/developer_testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&yearIsDateType=false&allowMultiQueries=true
    username: postgres
    password: YTyjy2018


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.kerninventor.demos.springsingtondemo.entity
