server:
  port: 8100

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&yearIsDateType=false&allowMultiQueries=true
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
    use-generated-keys: true